export { default as HomePage } from "./Home";
export { default as ProductDetailPage } from "./ProductDetail";
export { default as CartPage } from "./Cart";
export { default as OrderPage } from "./Order";
export { default as PaymentPage } from "./Payment";
export { default as OrderStatusPage } from "./OrderStatus";
export { default as UserProfilePage } from "./Profile/Profile";
export { default as ChangePasswordPage } from "./Profile/ChangePassword";
export { default as OrderHistoryPage } from "./Profile/OrderHistory";