# Generated by Django 6.0.5 on 2026-06-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_category_rejection_reason_category_verified_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="category",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Chờ duyệt"),
                    ("active", "Hoạt động"),
                    ("inactive", "Đã khóa"),
                    ("rejected", "Từ chối"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
