# Generated by Django 6.0.5 on 2026-06-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0005_category_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Chờ duyệt"),
                    ("active", "Hoạt động"),
                    ("inactive", "Đã khóa"),
                    ("rejected", "Từ chối"),
                    ("deleted", "Đã xóa"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
