"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def _env_bool(name: str, default: bool = False) -> bool:
    return os.environ.get(name, str(default)).lower() in ("true", "1", "yes")


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-dev-only-change-in-production",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DEBUG", True)

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]

RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RENDER_EXTERNAL_HOSTNAME}")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "apps.accounts",
    "apps.suppliers",
    "apps.categories",
    "apps.supplier_products",
    "apps.certifications",
    "apps.notifications",
]

# Cấu hình dùng JWT làm authentication mặc định
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Smart Green Market API",
    "DESCRIPTION": (
        "API cho nền tảng Smart Green Market — chợ nông sản xanh.\n\n"
        "## Xác thực\n"
        "Hầu hết endpoint yêu cầu header `Authorization: Bearer <access_token>`.\n"
        "Token lấy từ **Đăng ký** (`POST /api/register/`) hoặc **Đăng nhập** (`POST /api/login/`).\n\n"
        "## Luồng đăng ký Supplier (2 bước)\n"
        "1. **Bước 1** — `POST /api/register/` với `role=supplier` → nhận `access` + `refresh`.\n"
        "2. **Bước 2** — Dùng token vừa nhận:\n"
        "   - `POST /api/suppliers/` — tạo hồ sơ công ty\n"
        "   - `POST /api/supplier-documents/` — upload 3 giấy tờ một lần (multipart)\n\n"
        "## Luồng Admin duyệt Supplier\n"
        "1. `GET /api/suppliers/{supplier_id}/` — xem hồ sơ + `documents[]`\n"
        "2. `POST /api/supplier-documents/{document_id}/verify/` — duyệt từng giấy tờ\n"
        "3. `POST /api/suppliers/{supplier_id}/verify/` — duyệt supplier (cần đủ 3 giấy tờ approved)\n\n"
        "Supplier mới có `status=pending`, chờ Admin duyệt.\n\n"
        "## Vai trò (role)\n"
        "| Role | Mô tả |\n"
        "|------|-------|\n"
        "| `buyer` | Người mua — đăng ký xong dùng ngay (`status=active`) |\n"
        "| `supplier` | Nhà cung cấp — cần duyệt hồ sơ & giấy tờ |\n"
        "| `dealer` | Đại lý — cần duyệt tương tự supplier |\n"
        "| `admin` | Quản trị — duyệt supplier, document, sản phẩm, chứng nhận |\n"
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
    },
    "SECURITY": [{"BearerAuth": []}],
    "COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
                "description": "JWT access token. Lấy từ /api/register/ hoặc /api/login/",
            }
        }
    },
    "TAGS": [
        {
            "name": "Auth",
            "description": (
                "Đăng ký, đăng nhập, quản lý JWT và thông tin cá nhân. "
                "Endpoint register trả token ngay — không cần login riêng cho onboarding."
            ),
        },
        {
            "name": "Suppliers",
            "description": (
                "Quản lý hồ sơ nhà cung cấp. Supplier tạo profile sau khi đăng ký. "
                "Admin duyệt qua action `verify`."
            ),
        },
        {
            "name": "Supplier Documents",
            "description": (
                "Upload & quản lý giấy tờ nhà cung cấp (giấy phép KD, CMND, giấy thuế). "
                "Upload dạng multipart/form-data. Mỗi loại giấy tờ chỉ 1 file/supplier."
            ),
        },
        {
            "name": "Categories",
            "description": "Danh mục sản phẩm nông sản (Rau củ, Trái cây, ...). Yêu cầu tài khoản active.",
        },
        {
            "name": "Supplier Products",
            "description": (
                "Sản phẩm do supplier đăng bán. Chỉ supplier đã được duyệt mới tạo được. "
                "Sản phẩm mới ở trạng thái pending, chờ admin duyệt."
            ),
        },
        {
            "name": "Supplier Product Images",
            "description": "Ảnh sản phẩm. Một ảnh có thể đặt làm thumbnail (`is_thumbnail=true`).",
        },
        {
            "name": "Cultivation Processes",
            "description": "Quy trình canh tác từng bước của sản phẩm (minh bạch nguồn gốc).",
        },
        {
            "name": "Certifications",
            "description": "Chứng nhận chất lượng/organic của supplier. Admin duyệt qua action `verify`.",
        },
        {
            "name": "Notifications",
            "description": "Thông báo hệ thống. Dùng `/my/` để lấy thông báo của user hiện tại.",
        },
    ],
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

AUTH_USER_MODEL = "accounts.Account"

# Database — Render dùng DATABASE_URL; local dùng biến DB_* trong .env
DATABASE_URL = os.environ.get("DATABASE_URL")
if DATABASE_URL:
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=not DEBUG,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME", "smart_green_market"),
            "USER": os.environ.get("DB_USER", "postgres"),
            "PASSWORD": os.environ.get("DB_PASSWORD", ""),
            "HOST": os.environ.get("DB_HOST", "localhost"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
