"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def _env_bool(name: str, default: bool = False) -> bool:
    """Đọc biến môi trường dạng boolean (true/1/yes)."""
    return os.environ.get(name, str(default)).lower() in ("true", "1", "yes")


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-dev-only-change-in-production",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DEBUG", True)

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]

RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RENDER_EXTERNAL_HOSTNAME}")

# CORS — mặc định cho phép mọi origin (localhost + host deploy UI)
# Đặt CORS_ALLOW_ALL_ORIGINS=False và CORS_ALLOWED_ORIGINS=... nếu muốn giới hạn sau này
CORS_ALLOW_ALL_ORIGINS = _env_bool("CORS_ALLOW_ALL_ORIGINS", True)
if not CORS_ALLOW_ALL_ORIGINS:
    CORS_ALLOWED_ORIGINS = [
        origin.strip()
        for origin in os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",")
        if origin.strip()
    ]
CORS_ALLOW_CREDENTIALS = True

# URL frontend public để backend sinh link gian hàng đại lý.
# Deploy production nên set STOREFRONT_BASE_URL=https://domain-frontend
STOREFRONT_BASE_URL = os.environ.get(
    "STOREFRONT_BASE_URL",
    os.environ.get("FRONTEND_SITE_URL", "http://localhost:5173"),
).rstrip("/")

# URL public của backend (Swagger / tích hợp bên ngoài). Render: set env này.
API_PUBLIC_BASE_URL = os.environ.get(
    "API_PUBLIC_BASE_URL",
    "http://127.0.0.1:8000",
).rstrip("/")


# Application definition

CLOUDINARY_URL = os.environ.get("CLOUDINARY_URL")

if CLOUDINARY_URL:
    import cloudinary

    cloudinary.config(cloudinary_url=CLOUDINARY_URL, secure=True)

CLOUDINARY_STORAGE = (
    {
        "SECURE": True,
        "MEDIA_TAG": "smart-green-market",
    }
    if CLOUDINARY_URL
    else {}
)

INSTALLED_APPS = [
    "daphne",
    "channels",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "apps.accounts",
    "apps.suppliers",
    "apps.categories",
    "apps.product_catalog",
    "apps.supplier_products",
    "apps.dealers",
    "apps.dealer_products",
    "apps.customers",
    "apps.purchase_orders",
    "apps.orders",
    "apps.marketing",
    "apps.promotions",
    "apps.reviews",
    "apps.certifications",
    "apps.notifications",
    "apps.system_config",
    "apps.dashboard",
    "apps.voucher",
]

if CLOUDINARY_URL:
    # Không thêm cloudinary_storage app — tránh ghi đè collectstatic (lỗi Django 6)
    _staticfiles_index = INSTALLED_APPS.index("corsheaders")
    INSTALLED_APPS.insert(_staticfiles_index, "django.contrib.staticfiles")
    INSTALLED_APPS.insert(_staticfiles_index + 1, "cloudinary")
else:
    INSTALLED_APPS.insert(
        INSTALLED_APPS.index("corsheaders"),
        "django.contrib.staticfiles",
    )

# Cấu hình dùng JWT làm authentication mặc định
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_PAGINATION_CLASS": "common.pagination.LoadMorePagination",
    "EXCEPTION_HANDLER": "common.exceptions.custom_exception_handler",
    "PAGE_SIZE": 20,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=2),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Smart Green Market API",
    "DESCRIPTION": (
       
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "POSTPROCESSING_HOOKS": [
        "config.spectacular_hooks.postprocess_schema_servers",
    ],
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
        "docExpansion": "none",
        "filter": True,
    },
    "EXTENSIONS_ROOT": {
        "x-tagGroups": [
            {
                "name": "1. Hệ thống",
                "tags": ["Auth", "System Config", "Banks", "Account Documents"],
            },
            {
                "name": "2. Buyer — Gian hàng (B2C)",
                "tags": [
                    "Storefront Catalog",
                    "Storefront Auth",
                    "Storefront Customer",
                    "Storefront Addresses",
                ],
            },
            {
                "name": "3. Nhà cung cấp",
                "tags": [
                    "Suppliers",
                    "Supplier Products",
                    "Supplier Product Images",
                    "Cultivation Processes",
                    "Certifications",
                    "Certification Images",
                ],
            },
            {
                "name": "4. Đại lý & Kho",
                "tags": [
                    "Dealers",
                    "Dealer Customers",
                    "Categories",
                    "Dealer Products",
                    "Dealer Product Images",
                    "Dealer Inventory",
                    "Age Discount Policies",
                    "Purchase Orders",
                ],
            },
            {
                "name": "5. Thông báo",
                "tags": ["Notifications"],
            },
        ],
    },
    "SECURITY": [{"BearerAuth": []}],
    "COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
                "description": "JWT access token. Lấy từ /api/register/ hoặc /api/login/",
            }
        }
    },
    # Thứ tự tag trên Swagger UI — khai báo đủ tag và sắp theo luồng nghiệp vụ.
    "TAGS": [
        # --- 1. Hệ thống & xác thực ---
        {
            "name": "Auth",
            "description": (
                "Đăng ký, đăng nhập, quản lý JWT và thông tin cá nhân (supplier/dealer/admin). "
                "Upload avatar: `POST /api/profile/avatar/` — multipart, chọn file `avatar`. "
                "Endpoint register trả token ngay — không cần login riêng cho onboarding."
            ),
        },
        {
            "name": "System Config",
            "description": "Cấu hình giới hạn hệ thống (upload, danh mục, sản phẩm, đăng nhập).",
        },
        {
            "name": "Banks",
            "description": (
                "Danh sách ngân hàng Napas/VietQR cho dropdown cấu hình TK NCC. "
                "Lưu `bank_bin` + `bank_name` từ response khi PATCH supplier profile."
            ),
        },
        {
            "name": "Account Documents",
            "description": (
                "Upload & quản lý giấy tờ tài khoản supplier/dealer "
                "(giấy phép KD, CMND, giấy thuế). "
                "Swagger: multipart — chọn file cho từng loại giấy tờ. "
                "Mỗi loại giấy tờ chỉ 1 file/tài khoản."
            ),
        },
        # --- 2. Buyer — gian hàng đại lý (B2C) ---
        {
            "name": "Storefront Catalog",
            "description": (
                "Buyer duyệt catalog **không cần đăng nhập**: danh mục, tìm kiếm, chi tiết SP. "
                "Prefix URL: `/api/storefronts/{dealer_slug}/`."
            ),
        },
        {
            "name": "Storefront Auth",
            "description": (
                "Đăng ký / đăng nhập buyer theo từng gian hàng đại lý. "
                "Cùng email có thể đăng ký lại tại đại lý khác."
            ),
        },
        {
            "name": "Storefront Customer",
            "description": (
                "Buyer xem/cập nhật hồ sơ tại gian hàng đang đăng nhập. "
                "`PATCH .../me/` — multipart: chọn file `avatar`, cập nhật `full_name`, `phone`, "
                "`favorite_category`. Response trả `user.avatar_url` (read-only)."
            ),
        },
        {
            "name": "Storefront Addresses",
            "description": "Buyer quản lý địa chỉ nhận hàng trong gian hàng đại lý.",
        },
        # --- 3. Nhà cung cấp (B2B) ---
        {
            "name": "Suppliers",
            "description": (
                "Quản lý hồ sơ nhà cung cấp. Supplier tạo/cập nhật profile sau đăng ký "
                "(multipart — chọn file `logo`). Admin duyệt qua action `verify`. "
                "**Dealer:** `GET /api/suppliers/` (catalog NCC) → "
                "`GET /api/suppliers/{id}/products/` (chọn SP đặt hàng)."
            ),
        },
        {
            "name": "Supplier Products",
            "description": (
                "Sản phẩm do supplier đăng bán. Chỉ supplier đã được duyệt mới tạo được. "
                "Sản phẩm mới ở trạng thái pending, chờ admin duyệt."
            ),
        },
        {
            "name": "Supplier Product Images",
            "description": (
                "Upload & quản lý ảnh sản phẩm (multipart/form-data, field `images`). "
                "Một ảnh có thể đặt làm thumbnail (`is_thumbnail=true`)."
            ),
        },
        {
            "name": "Cultivation Processes",
            "description": "Quy trình canh tác từng bước của sản phẩm (minh bạch nguồn gốc).",
        },
        {
            "name": "Certifications",
            "description": (
                "Chứng nhận chất lượng/organic của supplier. "
                "Đăng ký kèm nhiều ảnh scan (field `images`). "
                "Thêm ảnh sau qua `/api/certification-images/`. Admin duyệt qua `verify`."
            ),
        },
        {
            "name": "Certification Images",
            "description": "Ảnh scan chứng nhận — upload/thay/xóa từng ảnh hoặc nhiều ảnh cùng lúc.",
        },
        # --- 4. Đại lý & kho ---
        {
            "name": "Dealers",
            "description": (
                "Quản lý hồ sơ đại lý. Dealer tạo/cập nhật profile sau đăng ký "
                "(multipart — chọn file `logo`). Admin duyệt qua `POST /api/dealers/{id}/verify/`. "
                "Link gian hàng: `GET /api/dealers/me/storefront-link/`."
            ),
        },
        {
            "name": "Dealer Customers",
            "description": "Đại lý xem tệp khách hàng đã đăng ký qua gian hàng của mình.",
        },
        {
            "name": "Categories",
            "description": "Danh mục sản phẩm nông sản (Rau củ, Trái cây, ...). Yêu cầu tài khoản active.",
        },
        {
            "name": "Dealer Products",
            "description": (
                "Sản phẩm bán lẻ của đại lý, gắn sản phẩm NCC. "
                "Admin duyệt qua action `verify`."
            ),
        },
        {
            "name": "Dealer Product Images",
            "description": "Ảnh sản phẩm đại lý (URL — field `image_url`).",
        },
        {
            "name": "Dealer Inventory",
            "description": (
                "Tồn kho lô hàng nhập từ phiếu nhập hoàn tất. "
                "Ghi hao hụt: `POST /api/dealer-inventory-batches/{id}/record-wastage/`. "
                "Giá theo tuổi hàng: `POST .../set-sale-price/`, `POST .../clear-sale-price/`. "
                "Ngày hết hạn: `POST .../set-expiry-date/`, `POST .../recompute-expiry-date/`, "
                "`POST .../backfill-expiry-dates/`."
            ),
        },
        {
            "name": "Age Discount Policies",
            "description": (
                "Chính sách giảm giá tự động theo tuổi lô (remaining_days, "
                "used_shelf_life_percent, age_days). Dealer cấu hình bậc giảm; "
                "giá hiệu lực tính trên từng `DealerInventoryBatch`."
            ),
        },
        {
            "name": "Purchase Orders",
            "description": (
                "Phiếu nhập hàng đại lý → NCC. Trước khi tạo đơn: "
                "`GET /api/suppliers/{id}/products/` để lấy `supplier_product_id`. "
                "Cấu hình đơn: `GET /api/purchase-order-config/`. "
                "Luồng: tạo đơn → NCC xác nhận → cọc → chuẩn bị → giao hàng → "
                "thanh toán cuối → hoàn tất. "
                "VietQR: `GET /api/purchase-orders/{id}/payment-qr/`."
            ),
        },
        # --- 5. Thông báo ---
        {
            "name": "Notifications",
            "description": (
                "Thông báo hệ thống (tiếng Việt). "
                "Dùng `GET /api/notifications/my/` — có `type_label`, `reference_type_label`, "
                "và `reference_status`/`reference_order_code` khi liên quan phiếu nhập."
            ),
        },
    ],
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

AUTH_USER_MODEL = "accounts.Account"

# Database — Render dùng DATABASE_URL; local dùng biến DB_* trong .env
DATABASE_URL = os.environ.get("DATABASE_URL")
DB_PASSWORD = os.environ.get("DB_PASSWORD", "")

if DATABASE_URL:
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=not DEBUG,
        )
    }
else:
    if not DB_PASSWORD:
        raise ImproperlyConfigured(
            "DB_PASSWORD is required. Set PostgreSQL credentials in backend/.env "
            "(DB_NAME, DB_USER, DB_PASSWORD, DB_HOST, DB_PORT)."
        )
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME", "smart_green_market"),
            "USER": os.environ.get("DB_USER", "postgres"),
            "PASSWORD": DB_PASSWORD,
            "HOST": os.environ.get("DB_HOST", "localhost"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

_STATICFILES_BACKEND = "whitenoise.storage.CompressedManifestStaticFilesStorage"
_DEFAULT_FILE_BACKEND = (
    "cloudinary_storage.storage.RawMediaCloudinaryStorage"
    if CLOUDINARY_URL
    else "django.core.files.storage.FileSystemStorage"
)

STORAGES = {
    "default": {
        "BACKEND": _DEFAULT_FILE_BACKEND,
    },
    "staticfiles": {
        "BACKEND": _STATICFILES_BACKEND,
    },
}


if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
ASGI_APPLICATION = "config.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/0")],
        },
    },
}