"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-q+2dx1o+-@)63drgp#((pt*)5uv5da&tn2_^i*mutwc5b)oa-x"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "apps.accounts",
    "apps.suppliers",
    "apps.categories",
    "apps.supplier_products",
    'apps.certifications',
    'apps.notifications',

]

# Cấu hình dùng JWT làm authentication mặc định
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Smart Green Market API",
    "DESCRIPTION": (
        "API cho nền tảng Smart Green Market — chợ nông sản xanh.\n\n"
        "## Xác thực\n"
        "Hầu hết endpoint yêu cầu header `Authorization: Bearer <access_token>`.\n"
        "Token lấy từ **Đăng ký** (`POST /api/register/`) hoặc **Đăng nhập** (`POST /api/login/`).\n\n"
        "## Luồng đăng ký Supplier (2 bước)\n"
        "1. **Bước 1** — `POST /api/register/` với `role=supplier` → nhận `access` + `refresh`.\n"
        "2. **Bước 2** — Dùng token vừa nhận:\n"
        "   - `POST /api/suppliers/` — tạo hồ sơ công ty\n"
        "   - `POST /api/supplier-documents/` — upload giấy tờ (multipart/form-data)\n\n"
        "Supplier mới có `status=pending`, chờ Admin duyệt.\n\n"
        "## Vai trò (role)\n"
        "| Role | Mô tả |\n"
        "|------|-------|\n"
        "| `buyer` | Người mua — đăng ký xong dùng ngay (`status=active`) |\n"
        "| `supplier` | Nhà cung cấp — cần duyệt hồ sơ & giấy tờ |\n"
        "| `dealer` | Đại lý — cần duyệt tương tự supplier |\n"
        "| `admin` | Quản trị — duyệt supplier, document, sản phẩm, chứng nhận |\n"
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SECURITY": [{"BearerAuth": []}],
    "COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
                "description": "JWT access token. Lấy từ /api/register/ hoặc /api/login/",
            }
        }
    },
    "TAGS": [
        {
            "name": "Auth",
            "description": (
                "Đăng ký, đăng nhập, quản lý JWT và thông tin cá nhân. "
                "Endpoint register trả token ngay — không cần login riêng cho onboarding."
            ),
        },
        {
            "name": "Suppliers",
            "description": (
                "Quản lý hồ sơ nhà cung cấp. Supplier tạo profile sau khi đăng ký. "
                "Admin duyệt qua action `verify`."
            ),
        },
        {
            "name": "Supplier Documents",
            "description": (
                "Upload & quản lý giấy tờ nhà cung cấp (giấy phép KD, CMND, giấy thuế). "
                "Upload dạng multipart/form-data. Mỗi loại giấy tờ chỉ 1 file/supplier."
            ),
        },
        {
            "name": "Categories",
            "description": "Danh mục sản phẩm nông sản (Rau củ, Trái cây, ...). Yêu cầu tài khoản active.",
        },
        {
            "name": "Supplier Products",
            "description": (
                "Sản phẩm do supplier đăng bán. Chỉ supplier đã được duyệt mới tạo được. "
                "Sản phẩm mới ở trạng thái pending, chờ admin duyệt."
            ),
        },
        {
            "name": "Supplier Product Images",
            "description": "Ảnh sản phẩm. Một ảnh có thể đặt làm thumbnail (`is_thumbnail=true`).",
        },
        {
            "name": "Cultivation Processes",
            "description": "Quy trình canh tác từng bước của sản phẩm (minh bạch nguồn gốc).",
        },
        {
            "name": "Certifications",
            "description": "Chứng nhận chất lượng/organic của supplier. Admin duyệt qua action `verify`.",
        },
        {
            "name": "Notifications",
            "description": "Thông báo hệ thống. Dùng `/my/` để lấy thông báo của user hiện tại.",
        },
    ],
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

AUTH_USER_MODEL = "accounts.Account"
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "smart_green_market",
        "USER": "postgres",
        "PASSWORD": "Nguyen+man1",
        "HOST": "localhost",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
