# Generated by Django 6.0.5 on 2026-06-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certifications", "0002_alter_certification_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certification",
            name="file_url",
            field=models.FileField(upload_to="certifications/"),
        ),
    ]
