# Generated by Django 6.0.5 on 2026-06-07 02:20

import django.db.models.deletion
from django.db import migrations, models


def copy_certification_files_to_images(apps, schema_editor):
    Certification = apps.get_model("certifications", "Certification")
    CertificationImage = apps.get_model("certifications", "CertificationImage")
    for cert in Certification.objects.all():
        file_field = cert.file_url
        if file_field and file_field.name:
            image = CertificationImage(
                certification=cert,
                sort_order=0,
            )
            image.image_url = file_field
            image.save()


class Migration(migrations.Migration):

    dependencies = [
        ("certifications", "0003_alter_certification_file_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificationImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.FileField(upload_to="certifications/")),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "certification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="certifications.certification",
                    ),
                ),
            ],
            options={
                "db_table": "certification_images",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.RunPython(
            copy_certification_files_to_images,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="certification",
            name="file_url",
        ),
    ]
