# Generated by Django 6.0.5 on 2026-06-10 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dealers", "0001_initial"),
        ("supplier_products", "0005_alter_supplierproduct_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DealerInventoryBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_order_item_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("batch_number", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField()),
                ("remaining_quantity", models.PositiveIntegerField()),
                ("import_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("import_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Đang hoạt động"),
                            ("depleted", "Hết hàng"),
                            ("expired", "Hết hạn"),
                            ("cancelled", "Đã hủy"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "dealer_inventory_batches",
                "ordering": ["-import_date", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DealerInventoryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("import", "Nhập kho"),
                            ("sale", "Bán hàng"),
                            ("wastage", "Hao hụt"),
                            ("adjustment", "Điều chỉnh"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity_before", models.IntegerField()),
                ("quantity_change", models.IntegerField()),
                ("quantity_after", models.IntegerField()),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="dealer_products.dealerinventorybatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dealer_inventory_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dealer_inventory_transactions",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DealerInventoryWastage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("reason", models.CharField(max_length=255)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wastages",
                        to="dealer_products.dealerinventorybatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dealer_inventory_wastages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dealer_inventory_wastages",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DealerProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("retail_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("thumbnail", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ duyệt"),
                            ("active", "Đang bán"),
                            ("inactive", "Ngừng bán"),
                            ("rejected", "Từ chối"),
                            ("deleted", "Đã xóa"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dealer_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="dealers.dealerprofile",
                    ),
                ),
                (
                    "supplier_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dealer_products",
                        to="supplier_products.supplierproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dealer Product",
                "verbose_name_plural": "Dealer Products",
                "db_table": "dealer_products",
                "ordering": ["-updated_at", "-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="dealerinventorybatch",
            name="dealer_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_batches",
                to="dealer_products.dealerproduct",
            ),
        ),
        migrations.CreateModel(
            name="DealerProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.CharField(max_length=500)),
                ("is_thumbnail", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dealer_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="dealer_products.dealerproduct",
                    ),
                ),
            ],
            options={
                "db_table": "dealer_product_images",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="dealerinventorybatch",
            constraint=models.UniqueConstraint(
                fields=("dealer_product", "batch_number"),
                name="unique_dealer_product_batch_number",
            ),
        ),
    ]
