# Generated by Django 6.0.5 on 2026-06-10 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dealerinventorybatch",
            name="purchase_order_item_id",
        ),
    ]
