# Generated by Django 6.0.5 on 2026-06-10 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_products", "0002_remove_dealerinventorybatch_purchase_order_item_id"),
        ("purchase_orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealerinventorybatch",
            name="purchase_order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dealer_inventory_batches",
                to="purchase_orders.purchaseorderitem",
            ),
        ),
    ]
