# Generated by Django 6.0.5 on 2026-06-14 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0004_alter_category_options_category_sort_order_and_more"),
        ("dealer_products", "0003_dealerinventorybatch_purchase_order_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealerproduct",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Danh mục bán lẻ do đại lý tạo và quản lý",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dealer_store_products",
                to="categories.category",
            ),
        ),
    ]
