# Generated by Django 6.0.5 on 2026-06-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_products", "0004_dealerproduct_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealerproductimage",
            name="image_url",
            field=models.FileField(upload_to="dealer_product_images/"),
        ),
    ]
