# Generated by Django 6.0.5 on 2026-06-28 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0006_age_discount"),
        ("dealer_products", "0005_dealer_product_image_filefield"),
        ("dealers", "0006_dealer_slug_store_code_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealerinventorybatch",
            name="manual_sale_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Giá bán thủ công — ưu tiên hơn chính sách giảm tự động",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AgeDiscountPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("all", "Tất cả sản phẩm"),
                            ("category", "Theo danh mục"),
                            ("dealer_product", "Theo sản phẩm đại lý"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "threshold_type",
                    models.CharField(
                        choices=[
                            ("remaining_days", "Số ngày còn lại trước hết hạn"),
                            ("used_shelf_life_percent", "% tuổi bảo quản đã qua"),
                            ("age_days", "Số ngày tồn kho"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0, help_text="Cao hơn thắng khi nhiều policy cùng scope"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="age_discount_policies",
                        to="categories.category",
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="age_discount_policies",
                        to="dealers.dealerprofile",
                    ),
                ),
                (
                    "dealer_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="age_discount_policies",
                        to="dealer_products.dealerproduct",
                    ),
                ),
            ],
            options={
                "db_table": "age_discount_policies",
                "ordering": ["-priority", "-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AgeDiscountTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("gte", ">="),
                            ("lte", "<="),
                            ("gt", ">"),
                            ("lt", "<"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "threshold_value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percent", "Theo phần trăm"),
                            ("fixed", "Số tiền cố định"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Cao hơn thắng khi nhiều tier cùng thỏa"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="dealer_products.agediscountpolicy",
                    ),
                ),
            ],
            options={
                "db_table": "age_discount_tiers",
                "ordering": ["-sort_order", "-id"],
            },
        ),
    ]
