# Generated by Django 6.0.5 on 2026-06-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_products", "0007_dealerinventorybatch_production_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealerinventorytransaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("import", "Nhập kho"),
                    ("sale", "Bán hàng"),
                    ("cancel_restore", "Hoàn tồn do hủy đơn"),
                    ("wastage", "Hao hụt"),
                    ("adjustment", "Điều chỉnh"),
                ],
                max_length=20,
            ),
        ),
    ]
