# Generated by Django 6.0.5 on 2026-07-02 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_products", "0008_alter_dealerinventorytransaction_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="DealerProductRelatedRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "related_product_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Danh sách dealer_product.id được gợi ý, theo thứ tự ưu tiên",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dealer_product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_recommendation",
                        to="dealer_products.dealerproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dealer Product Related Recommendation",
                "verbose_name_plural": "Dealer Product Related Recommendations",
                "db_table": "dealer_product_related_recommendations",
                "ordering": ["-updated_at", "-id"],
            },
        ),
    ]
