# Generated by Django 6.0.5 on 2026-07-02 03:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_products", "0009_dealerproductrelatedrecommendation"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION jsonb_to_int_array(val jsonb)
            RETURNS integer[] AS $$
                SELECT COALESCE(
                    array_agg(elem::integer ORDER BY ord),
                    ARRAY[]::integer[]
                )
                FROM jsonb_array_elements_text(COALESCE(val, '[]'::jsonb))
                    WITH ORDINALITY AS t(elem, ord);
            $$ LANGUAGE sql IMMUTABLE;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS jsonb_to_int_array(jsonb);",
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="dealerproductrelatedrecommendation",
                    name="related_product_ids",
                    field=django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        help_text="Danh sách dealer_product.id được gợi ý, theo thứ tự ưu tiên",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE dealer_product_related_recommendations
                    ALTER COLUMN related_product_ids TYPE integer[]
                    USING jsonb_to_int_array(related_product_ids);
                    """,
                    reverse_sql="""
                    ALTER TABLE dealer_product_related_recommendations
                    ALTER COLUMN related_product_ids TYPE jsonb
                    USING to_jsonb(COALESCE(related_product_ids, ARRAY[]::integer[]));
                    """,
                ),
            ],
        ),
        migrations.RunSQL(
            sql="DROP FUNCTION IF EXISTS jsonb_to_int_array(jsonb);",
            reverse_sql="""
            CREATE OR REPLACE FUNCTION jsonb_to_int_array(val jsonb)
            RETURNS integer[] AS $$
                SELECT COALESCE(
                    array_agg(elem::integer ORDER BY ord),
                    ARRAY[]::integer[]
                )
                FROM jsonb_array_elements_text(COALESCE(val, '[]'::jsonb))
                    WITH ORDINALITY AS t(elem, ord);
            $$ LANGUAGE sql IMMUTABLE;
            """,
        ),
    ]
