# Generated by Django 6.0.5 on 2026-07-16 08:06

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0006_age_discount"),
        ("dealer_products", "0016_cleanup_orphan_inventory_batches"),
        ("dealers", "0006_dealer_slug_store_code_help_text"),
        ("product_catalog", "0004_remove_season"),
        ("supplier_products", "0009_quantity_discount_policy"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dealerproduct",
            name="unique_dealer_product_title_per_dealer_no_master",
        ),
        migrations.AddConstraint(
            model_name="dealerproduct",
            constraint=models.UniqueConstraint(
                models.F("dealer_profile"),
                django.db.models.functions.text.Lower("title"),
                condition=models.Q(
                    ("product_master__isnull", True),
                    ("status__in", ["pending", "active", "inactive", "rejected"]),
                ),
                name="unique_dealer_product_title_per_dealer_no_master",
            ),
        ),
    ]
