# Generated by Django 6.0.5 on 2026-06-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notificationreceipt',
            options={'ordering': ['-notification__created_at']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', 'Thông tin'), ('warning', 'Cảnh báo'), ('success', 'Thành công'), ('error', 'Thất bại')], max_length=20),
        ),
    ]
