# Generated by Django 6.0.5 on 2026-06-15 05:31

from django.db import migrations, models
from django.utils.text import slugify


def populate_dealer_slugs(apps, schema_editor):
    DealerProfile = apps.get_model("dealers", "DealerProfile")
    for dealer in DealerProfile.objects.filter(slug__isnull=True):
        base_slug = slugify(dealer.store_name) or f"dealer-{dealer.account_id}"
        base_slug = base_slug[:240]
        slug = base_slug
        suffix = 1
        while DealerProfile.objects.filter(slug=slug).exclude(pk=dealer.pk).exists():
            suffix += 1
            slug = f"{base_slug}-{suffix}"[:255]
        dealer.slug = slug
        dealer.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("dealers", "0002_dealerprofile_verification_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealerprofile",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(populate_dealer_slugs, migrations.RunPython.noop),
    ]
