# Generated by Django 6.0.5 on 2026-06-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealers", "0003_dealerprofile_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealerprofile",
            name="logo",
            field=models.FileField(blank=True, null=True, upload_to="dealer_logos/"),
        ),
    ]
