# Generated by Django 6.0.5 on 2026-06-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealers", "0005_regenerate_dealer_store_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealerprofile",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Mã cửa hàng công khai (xxx-yyy-zzz), tự sinh — không đổi khi đổi tên",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
