export { default as AdminLoginPage } from "./AdminLoginPage";
export { default as SettingPage } from "./Setting";
export { default as SupplierPage } from "./Suppiler";
export { default as CategoryPage } from "./Category";
export { default as ProductPage } from "./Product";
export { default as CertificationPage } from "./Certification";
export { default as DocumentPage } from "./Document";
export { default as NotificationPage } from "./Notification";
export { default as DealerPage } from "./Dealer";
