# Generated by Django 6.0.5 on 2026-06-26 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_upload_image_size_mb",
                    models.PositiveSmallIntegerField(default=5),
                ),
                (
                    "max_categories_per_supplier",
                    models.PositiveSmallIntegerField(default=5),
                ),
                (
                    "max_products_per_supplier",
                    models.PositiveSmallIntegerField(default=100),
                ),
                ("max_images_per_product", models.PositiveSmallIntegerField(default=5)),
                (
                    "max_images_per_certification",
                    models.PositiveSmallIntegerField(default=5),
                ),
                ("max_login_attempts", models.PositiveSmallIntegerField(default=5)),
                ("login_lockout_minutes", models.PositiveSmallIntegerField(default=15)),
                ("min_order_amount", models.PositiveBigIntegerField(default=500000)),
                ("max_order_amount", models.PositiveBigIntegerField(default=500000000)),
                ("min_deposit_percent", models.PositiveSmallIntegerField(default=10)),
                ("max_deposit_percent", models.PositiveSmallIntegerField(default=50)),
                (
                    "default_deposit_percent",
                    models.PositiveSmallIntegerField(default=30),
                ),
                ("min_delivery_lead_days", models.PositiveSmallIntegerField(default=2)),
                ("shipping_fee", models.PositiveIntegerField(default=10000)),
                ("min_lead_hours", models.PositiveSmallIntegerField(default=6)),
                ("morning_cutoff_hour", models.PositiveSmallIntegerField(default=23)),
                ("max_booking_days", models.PositiveSmallIntegerField(default=2)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_settings_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
                "db_table": "system_settings",
            },
        ),
    ]
