# Generated by Django 6.0.5 on 2026-06-16 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0002_remove_dealercustomer_unique_dealer_customer_and_more"),
        ("dealer_products", "0004_dealerproduct_category"),
        ("dealers", "0004_dealerprofile_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_code", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ xác nhận"),
                            ("confirmed", "Đã xác nhận"),
                            ("processing", "Đang chuẩn bị"),
                            ("shipping", "Đang giao"),
                            ("delivered", "Đã giao"),
                            ("completed", "Hoàn tất"),
                            ("cancelled", "Đã hủy"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("receiver_name", models.CharField(max_length=255)),
                ("receiver_phone", models.CharField(max_length=20)),
                ("delivery_address", models.TextField()),
                ("delivery_time", models.DateTimeField()),
                ("note", models.TextField(blank=True)),
                (
                    "subtotal_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "shipping_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "debt_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Số tiền còn phải thanh toán",
                        max_digits=14,
                    ),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="customers.customerprofile",
                    ),
                ),
                (
                    "customer_address",
                    models.ForeignKey(
                        blank=True,
                        help_text="Địa chỉ gốc buyer chọn — snapshot lưu ở receiver/delivery fields",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="customers.customeraddress",
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_orders",
                        to="dealers.dealerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "orders",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CustomerPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Tiền mặt"),
                            ("bank_transfer", "Chuyển khoản"),
                            ("e_wallet", "Ví điện tử"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_provider",
                    models.CharField(
                        blank=True,
                        choices=[("momo", "MoMo"), ("vnpay", "VNPay")],
                        max_length=50,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("full", "Thanh toán đủ"),
                            ("cod", "Thanh toán khi nhận hàng"),
                        ],
                        default="full",
                        max_length=20,
                    ),
                ),
                ("transaction_code", models.CharField(blank=True, max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ thanh toán"),
                            ("paid", "Đã thanh toán"),
                            ("failed", "Thất bại"),
                            ("refunded", "Đã hoàn tiền"),
                            ("cancelled", "Đã hủy"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "receipt_file",
                    models.FileField(
                        blank=True, upload_to="customer_payment_receipts/"
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("note", models.TextField(blank=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_customer_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "customer_payments",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_title", models.CharField(max_length=255)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "import_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Giá nhập snapshot — phục vụ báo cáo margin đại lý",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=14)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="dealer_products.dealerinventorybatch",
                    ),
                ),
                (
                    "dealer_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="dealer_products.dealerproduct",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "order_items",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(blank=True, max_length=20)),
                ("new_status", models.CharField(max_length=20)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_order_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_histories",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "order_status_histories",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["dealer", "status"], name="orders_dealer__3b814b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer", "-created_at"], name="orders_custome_12b615_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customerpayment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("payment_provider__gt", ""), ("transaction_code__gt", "")
                ),
                fields=("payment_provider", "transaction_code"),
                name="unique_customer_payment_provider_transaction",
            ),
        ),
    ]
