# Generated by Django 6.0.5 on 2026-07-07 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_remove_dealercustomer_unique_dealer_customer_and_more"),
        ("dealer_products", "0013_return_restore_transaction_type"),
        ("dealers", "0006_dealer_slug_store_code_help_text"),
        ("orders", "0002_order_cancel_reason_order_cancelled_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Chờ xác nhận"),
                    ("confirmed", "Đã xác nhận"),
                    ("processing", "Đang chuẩn bị"),
                    ("shipping", "Đang giao"),
                    ("delivered", "Đã giao"),
                    ("completed", "Hoàn tất"),
                    ("cancel_requested", "Yêu cầu hủy"),
                    ("delivery_failed", "Giao thất bại"),
                    ("return_requested", "Yêu cầu trả hàng"),
                    ("return_approved", "Đã duyệt trả hàng"),
                    ("return_rejected", "Từ chối trả hàng"),
                    ("returned", "Đã trả hàng"),
                    ("cancelled", "Đã hủy"),
                    ("waiting_stock", "Chờ hàng về kho"),
                    ("delivery_reschedule_proposed", "Chờ xác nhận đổi ngày giao"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                help_text="Null khi đơn waiting_stock chưa được phân bổ lô",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="dealer_products.dealerinventorybatch",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="new_status",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="old_status",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name="PreOrderRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_code", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Đã gửi — chờ đại lý"),
                            ("customer_confirmation_pending", "Chờ khách xác nhận"),
                            ("rejected_by_dealer", "Đại lý từ chối"),
                            ("rejected_by_customer", "Khách từ chối"),
                            ("converted", "Đã chuyển thành đơn"),
                            ("cancelled", "Đã hủy"),
                        ],
                        default="submitted",
                        max_length=32,
                    ),
                ),
                ("receiver_name", models.CharField(max_length=255)),
                ("receiver_phone", models.CharField(max_length=20)),
                ("delivery_address", models.TextField()),
                ("requested_delivery_time", models.DateTimeField()),
                (
                    "confirmed_delivery_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("proposed_delivery_time", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("dealer_note", models.TextField(blank=True)),
                ("reject_reason", models.TextField(blank=True)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "converted_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_preorder_requests",
                        to="orders.order",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preorder_requests",
                        to="customers.customerprofile",
                    ),
                ),
                (
                    "customer_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preorder_requests",
                        to="customers.customeraddress",
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preorder_requests",
                        to="dealers.dealerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "preorder_requests",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PreOrderRequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_title", models.CharField(max_length=255)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("requested_quantity", models.PositiveIntegerField()),
                ("available_at_submit", models.PositiveIntegerField(default=0)),
                (
                    "confirmed_quantity",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "proposed_quantity",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "dealer_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preorder_request_items",
                        to="dealer_products.dealerproduct",
                    ),
                ),
                (
                    "preorder_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.preorderrequest",
                    ),
                ),
            ],
            options={
                "db_table": "preorder_request_items",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="preorderrequest",
            index=models.Index(
                fields=["dealer", "status"], name="preorder_re_dealer__b26741_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="preorderrequest",
            index=models.Index(
                fields=["customer", "-created_at"],
                name="preorder_re_custome_b55a9b_idx",
            ),
        ),
    ]
