# Generated by Django 6.0.5 on 2026-07-09 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_id', models.IntegerField(db_index=True)),
                ('dealer_product_id', models.IntegerField(db_index=True)),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('recent_avg_daily_sales', models.FloatField(default=0.0)),
                ('growth_rate', models.FloatField(default=0.0)),
                ('trend_label', models.CharField(max_length=50)),
                ('forecast_next_days', models.JSONField(default=list)),
                ('stock_days_left', models.FloatField(default=0.0)),
                ('days_to_nearest_expiry', models.IntegerField(default=30)),
                ('decision', models.CharField(max_length=100)),
                ('decision_confidence', models.FloatField(default=0.0)),
                ('all_probabilities', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'dealer_product_prediction_results',
                'unique_together': {('dealer_id', 'dealer_product_id')},
            },
        ),
    ]
