# Generated by Django 6.0.5 on 2026-07-10 03:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITrainingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='Item2Vec', max_length=50)),
                ('run_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('epochs_run', models.IntegerField(help_text='Số epoch thực tế đã chạy (sau khi EarlyStopping)')),
                ('final_loss', models.FloatField(help_text='Độ suy hao (Loss) ở epoch cuối cùng')),
                ('catalog_coverage', models.FloatField(help_text='Độ phủ danh mục (%)')),
                ('total_items_trained', models.IntegerField(help_text='Tổng số sản phẩm tham gia huấn luyện')),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
            ],
            options={
                'db_table': 'ai_training_history',
                'ordering': ['-run_date'],
            },
        ),
    ]
