# Generated by Django 6.0.5 on 2026-07-19 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_models', '0002_aitraininghistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aitraininghistory',
            options={'ordering': ['-run_date'], 'verbose_name': 'Lịch sử Hệ thống Phân tích Gợi ý', 'verbose_name_plural': 'Lịch sử Hệ thống Phân tích Gợi ý'},
        ),
        migrations.AddField(
            model_name='aitraininghistory',
            name='dealer_coverage_detail',
            field=models.JSONField(default=list, help_text='Chi tiết khả năng AI hỗ trợ từng cửa hàng (Tỷ lệ sản phẩm được AI ưu tiên gợi ý)', verbose_name='Chi tiết hiệu quả theo Cửa hàng'),
        ),
        migrations.AddField(
            model_name='aitraininghistory',
            name='loss_history',
            field=models.JSONField(default=list, help_text='Dữ liệu biểu diễn mức độ cải thiện của AI qua từng chu kỳ học', verbose_name='Biểu đồ học hỏi'),
        ),
        migrations.AlterField(
            model_name='aitraininghistory',
            name='catalog_coverage',
            field=models.FloatField(help_text='Tỷ lệ % sản phẩm hệ thống có đủ dữ liệu để hỗ trợ gợi ý', verbose_name='Tỷ lệ bao phủ sản phẩm'),
        ),
        migrations.AlterField(
            model_name='aitraininghistory',
            name='epochs_run',
            field=models.IntegerField(help_text='Số chu kỳ học (vòng lặp) để AI nắm bắt dữ liệu', verbose_name='Chu kỳ học'),
        ),
        migrations.AlterField(
            model_name='aitraininghistory',
            name='final_loss',
            field=models.FloatField(help_text='Độ sai lệch (càng thấp càng tốt)', verbose_name='Chỉ số sai lệch (Loss)'),
        ),
        migrations.AlterField(
            model_name='aitraininghistory',
            name='model_name',
            field=models.CharField(default='Item2Vec', max_length=50, verbose_name='Thuật toán áp dụng'),
        ),
        migrations.AlterField(
            model_name='aitraininghistory',
            name='run_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian chạy'),
        ),
        migrations.AlterField(
            model_name='aitraininghistory',
            name='status',
            field=models.CharField(default='SUCCESS', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='aitraininghistory',
            name='total_items_trained',
            field=models.IntegerField(help_text='Số lượng sản phẩm đủ điều kiện tham gia phân tích', verbose_name='Tổng sản phẩm phân tích'),
        ),
    ]
