# Generated by Django 6.0.5 on 2026-06-10 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dealers", "0001_initial"),
        ("supplier_products", "0006_supplierproduct_wholesale_price"),
        ("suppliers", "0006_supplier_bank_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_code", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_supplier_confirmation", "Chờ NCC xác nhận"),
                            ("rejected", "NCC từ chối"),
                            ("confirmed", "NCC đã xác nhận"),
                            ("deposit_pending_verification", "Chờ xác nhận tiền cọc"),
                            ("deposit_paid", "Đã thanh toán cọc"),
                            ("processing", "Đang chuẩn bị hàng"),
                            ("shipping", "Đang giao hàng"),
                            ("delivered", "Đã giao hàng"),
                            (
                                "final_payment_pending_verification",
                                "Chờ xác nhận thanh toán cuối",
                            ),
                            ("completed", "Hoàn tất"),
                            ("cancelled", "Đã hủy"),
                        ],
                        default="pending_supplier_confirmation",
                        max_length=40,
                    ),
                ),
                ("delivery_address", models.TextField()),
                ("requested_delivery_time", models.DateTimeField()),
                ("receiver_name", models.CharField(max_length=255)),
                ("receiver_phone", models.CharField(max_length=20)),
                ("note", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "deposit_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tỷ lệ đặt cọc (%), ví dụ 30",
                        max_digits=5,
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tổng tiền đã xác nhận thanh toán",
                        max_digits=14,
                    ),
                ),
                (
                    "debt_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Số tiền còn phải thanh toán",
                        max_digits=14,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="dealers.dealerprofile",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_orders",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=14)),
                ("note", models.TextField(blank=True)),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchase_orders.purchaseorder",
                    ),
                ),
                (
                    "supplier_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_order_items",
                        to="supplier_products.supplierproduct",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_order_items",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Tiền mặt"),
                            ("bank_transfer", "Chuyển khoản"),
                            ("e_wallet", "Ví điện tử"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payment_provider", models.CharField(blank=True, max_length=50)),
                ("transaction_code", models.CharField(blank=True, max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Đặt cọc"),
                            ("final_payment", "Thanh toán cuối"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ xác nhận"),
                            ("verified", "Đã xác nhận"),
                            ("rejected", "Từ chối"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "receipt_file",
                    models.FileField(blank=True, upload_to="payment_receipts/"),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("note", models.TextField(blank=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="purchase_orders.purchaseorder",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_purchase_order_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "purchase_order_payments",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(blank=True, max_length=40)),
                ("new_status", models.CharField(max_length=40)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_order_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_histories",
                        to="purchase_orders.purchaseorder",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_order_status_histories",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
