# Generated by Django 6.0.5 on 2026-06-29 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_orders", "0002_confirmed_delivery_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="cancel_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_purchase_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_supplier_confirmation", "Chờ NCC xác nhận"),
                    ("rejected", "NCC từ chối"),
                    ("confirmed", "NCC đã xác nhận"),
                    ("deposit_pending_verification", "Chờ xác nhận tiền cọc"),
                    ("deposit_paid", "Đã thanh toán cọc"),
                    ("processing", "Đang chuẩn bị hàng"),
                    ("shipping", "Đang giao hàng"),
                    ("delivered", "Đã giao hàng"),
                    (
                        "final_payment_pending_verification",
                        "Chờ xác nhận thanh toán cuối",
                    ),
                    ("return_requested", "Yêu cầu trả hàng"),
                    ("return_approved", "Đã duyệt trả hàng"),
                    ("return_rejected", "Từ chối trả hàng"),
                    ("returned", "Đã trả hàng"),
                    ("completed", "Hoàn tất"),
                    ("cancelled", "Đã hủy"),
                ],
                default="pending_supplier_confirmation",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Chờ xác nhận"),
                    ("verified", "Đã xác nhận"),
                    ("rejected", "Từ chối"),
                    ("cancelled", "Đã hủy"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PurchaseOrderReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Chờ xử lý"),
                            ("approved", "Đã duyệt"),
                            ("rejected", "Từ chối"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "evidence_file",
                    models.FileField(blank=True, upload_to="purchase_order_returns/"),
                ),
                (
                    "refund_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("review_note", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returns",
                        to="purchase_orders.purchaseorder",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_purchase_order_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_purchase_order_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "purchase_order_returns",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("reason", models.TextField(blank=True)),
                (
                    "purchase_order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_items",
                        to="purchase_orders.purchaseorderitem",
                    ),
                ),
                (
                    "purchase_order_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchase_orders.purchaseorderreturn",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_order_return_items",
                "ordering": ["id"],
            },
        ),
    ]
