# Generated by Django 6.0.5 on 2026-06-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierdocument",
            name="file_url",
            field=models.FileField(upload_to="documents/"),
        ),
    ]
