# Generated by Django 6.0.5 on 2026-06-06 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0002_alter_supplierdocument_file_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_suppliers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Chờ duyệt"),
                    ("approved", "Đã duyệt"),
                    ("rejected", "Từ chối"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="supplierdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("business_license", "Giấy phép kinh doanh"),
                    ("id_card", "CMND/CCCD"),
                    ("tax_certificate", "Giấy chứng nhận thuế"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="supplierdocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Chờ duyệt"),
                    ("approved", "Đã duyệt"),
                    ("rejected", "Từ chối"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
