# Generated by Django 6.0.5 on 2026-06-07 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0003_supplier_rejection_reason_supplier_verified_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplier",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
            },
        ),
        migrations.AlterModelOptions(
            name="supplierdocument",
            options={
                "ordering": ["document_type", "-created_at"],
                "verbose_name": "Supplier Document",
                "verbose_name_plural": "Supplier Documents",
            },
        ),
    ]
