# Generated by Django 6.0.5 on 2026-06-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0004_alter_supplier_options_and_more"),
        ("accounts", "0006_migrate_supplier_documents"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="supplierdocument",
            name="unique_supplier_document_type",
        ),
        migrations.DeleteModel(
            name="SupplierDocument",
        ),
    ]
