# Generated by Django 6.0.5 on 2026-06-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "suppliers",
            "0005_remove_supplierdocument_unique_supplier_document_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="account_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="supplier",
            name="account_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="supplier",
            name="bank_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
