# Generated by Django 6.0.5 on 2026-06-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0006_supplier_bank_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="bank_bin",
            field=models.CharField(
                blank=True,
                help_text="Mã BIN Napas 6 số (vd. Vietcombank=970436) — dùng sinh VietQR",
                max_length=6,
            ),
        ),
    ]
