# Generated by Django 6.0.5 on 2026-06-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0007_supplier_bank_bin"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="logo",
            field=models.FileField(blank=True, null=True, upload_to="supplier_logos/"),
        ),
    ]
