# Generated by Django 6.0.5 on 2026-06-16 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0005_category_scope"),
        ("dealer_products", "0004_dealerproduct_category"),
        ("dealers", "0004_dealerprofile_logo"),
        ("marketing", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "code",
                    models.CharField(
                        blank=True, help_text="Mã voucher, vd. SUMMER10", max_length=50
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percent", "Theo phần trăm"),
                            ("fixed", "Số tiền cố định"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Trần giảm khi discount_type=percent",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Tổng lượt dùng tối đa — null = không giới hạn",
                        null=True,
                    ),
                ),
                (
                    "usage_limit_per_customer",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Lượt dùng tối đa mỗi khách — null = không giới hạn",
                        null=True,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Nháp"),
                            ("active", "Đang chạy"),
                            ("inactive", "Tạm dừng"),
                            ("expired", "Hết hạn"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_promotions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        blank=True,
                        help_text="null = khuyến mãi toàn sàn do admin tạo",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="dealers.dealerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "promotions",
                "ordering": ["-start_date", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PromotionTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("all", "Tất cả khách / sản phẩm"),
                            ("segment", "Theo nhóm khách"),
                            ("product", "Theo sản phẩm đại lý"),
                            ("category", "Theo danh mục"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_targets",
                        to="categories.category",
                    ),
                ),
                (
                    "dealer_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_targets",
                        to="dealer_products.dealerproduct",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="promotions.promotion",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_targets",
                        to="marketing.customersegment",
                    ),
                ),
            ],
            options={
                "db_table": "promotion_targets",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PromotionUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_usages",
                        to="orders.order",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usages",
                        to="promotions.promotion",
                    ),
                ),
            ],
            options={
                "db_table": "promotion_usages",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code__gt", "")),
                fields=("dealer", "code"),
                name="unique_promotion_code_per_dealer",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotionusage",
            constraint=models.UniqueConstraint(
                fields=("promotion", "order"), name="unique_promotion_usage_per_order"
            ),
        ),
    ]
