# Generated by Django 6.0.5 on 2026-06-30 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_dealercustomer_unique_dealer_customer_and_more'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='promotion',
            name='unique_promotion_code_per_dealer',
        ),
        migrations.AddField(
            model_name='promotion',
            name='applicable_scope',
            field=models.CharField(choices=[('ALL', 'Tất cả'), ('SEGMENT', 'Nhóm khách'), ('CUSTOMER', 'Khách hàng'), ('DEALER', 'Đại lý'), ('CATEGORY', 'Danh mục'), ('PRODUCT', 'Sản phẩm')], default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='promotion',
            name='max_usage_per_customer',
            field=models.IntegerField(blank=True, help_text='Lượt dùng tối đa mỗi khách — null = không giới hạn', null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='min_order_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='promotion',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='remaining_quantity',
            field=models.IntegerField(blank=True, help_text='Số lượt dùng còn lại — null = không giới hạn', null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='total_quantity',
            field=models.IntegerField(blank=True, help_text='Tổng lượt dùng tối đa — null = không giới hạn', null=True),
        ),
        migrations.AddField(
            model_name='promotiontarget',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_targets', to='customers.customerprofile'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(blank=True, help_text='Mã voucher, vd. SUMMER10. null = tự động hiển thị cho khách chọn.', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('pending', 'Chờ duyệt'), ('active', 'Đang chạy'), ('inactive', 'Tạm dừng'), ('expired', 'Hết hạn'), ('rejected', 'Từ chối')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='promotiontarget',
            name='target_type',
            field=models.CharField(choices=[('all', 'Tất cả khách / sản phẩm'), ('segment', 'Theo nhóm khách'), ('product', 'Theo sản phẩm đại lý'), ('category', 'Theo danh mục'), ('customer', 'Theo khách hàng'), ('dealer', 'Theo đại lý')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='min_order_amount',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='usage_limit',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='usage_limit_per_customer',
        ),
    ]
