# Generated by Django 6.0.5 on 2026-06-30 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0006_dealer_slug_store_code_help_text'),
        ('promotions', '0002_remove_promotion_unique_promotion_code_per_dealer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='applicable_scope',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='max_usage_per_customer',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='min_order_value',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='reject_reason',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='remaining_quantity',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='total_quantity',
        ),
        migrations.AddField(
            model_name='promotion',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='promotion',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Tổng lượt dùng tối đa — null = không giới hạn', null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='usage_limit_per_customer',
            field=models.PositiveIntegerField(blank=True, help_text='Lượt dùng tối đa mỗi khách — null = không giới hạn', null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(blank=True, help_text='Mã voucher, vd. SUMMER10', max_length=50),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('active', 'Đang chạy'), ('inactive', 'Tạm dừng'), ('expired', 'Hết hạn')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='promotiontarget',
            name='target_type',
            field=models.CharField(choices=[('all', 'Tất cả khách / sản phẩm'), ('segment', 'Theo nhóm khách'), ('product', 'Theo sản phẩm đại lý'), ('category', 'Theo danh mục'), ('customer', 'Theo khách hàng')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.UniqueConstraint(condition=models.Q(('code__gt', '')), fields=('dealer', 'code'), name='unique_promotion_code_per_dealer'),
        ),
    ]
