# Generated by Django 6.0.5 on 2026-06-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_remove_promotion_applicable_scope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('pending', 'Chờ duyệt'), ('active', 'Đang chạy'), ('inactive', 'Tạm dừng'), ('expired', 'Hết hạn'), ('rejected', 'Từ chối')], default='pending', max_length=20),
        ),
    ]
