# Generated by Django 6.0.5 on 2026-06-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_alter_promotion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='reject_reason',
            field=models.TextField(blank=True, help_text='Lý do từ chối duyệt voucher', null=True),
        ),
    ]
