# Generated by Django 6.0.5 on 2026-06-30 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_promotion_reject_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(help_text='Mã voucher, vd. SUMMER10', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_code', message='Mã voucher chỉ được chứa chữ cái không dấu, chữ số, dấu gạch ngang (-) và gạch dưới (_), không chứa khoảng trắng.', regex='^[a-zA-Z0-9_-]+$')]),
        ),
    ]
