# Generated by Django 6.0.5 on 2026-07-07 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0008_promotion_daily_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(error_messages={'unique': 'Mã voucher này đã tồn tại trong gian hàng của bạn.'}, help_text='Mã voucher, vd. SUMMER10', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_code', message='Mã voucher chỉ được chứa chữ cái không dấu, chữ số, dấu gạch ngang (-) và gạch dưới (_), không chứa khoảng trắng.', regex='^[a-zA-Z0-9_-]+$')]),
        ),
    ]
