# Generated by Django 6.0.5 on 2026-07-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loyalty", "0002_seed_default_loyalty"),
        ("promotions", "0009_alter_promotion_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="audience_type",
            field=models.CharField(
                choices=[
                    ("ALL", "Tất cả khách hàng"),
                    ("LOYALTY_TIER", "Theo hạng thành viên"),
                    ("CUSTOMER_SEGMENT", "Theo phân khúc khách hàng"),
                ],
                default="ALL",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="loyalty_tiers",
            field=models.ManyToManyField(
                blank=True, related_name="promotions", to="loyalty.loyaltytier"
            ),
        ),
    ]
