# Generated by Django 6.0.5 on 2026-06-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("banned", "Banned"),
                    ("pending", "Pending"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
