# Generated by Django 6.0.5 on 2026-06-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_loginattempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="avatar",
            field=models.FileField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
