# Generated by Django 6.0.5 on 2026-06-10 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_account_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("business_license", "Giấy phép kinh doanh"),
                            ("id_card", "CMND/CCCD"),
                            ("tax_certificate", "Giấy chứng nhận thuế"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file_url", models.FileField(upload_to="documents/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ duyệt"),
                            ("approved", "Đã duyệt"),
                            ("rejected", "Từ chối"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_account_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Document",
                "verbose_name_plural": "Account Documents",
                "db_table": "account_documents",
                "ordering": ["document_type", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "document_type"),
                        name="unique_account_document_type",
                    )
                ],
            },
        ),
    ]
