# Generated by Django 6.0.5 on 2026-06-15 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_migrate_supplier_documents"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("dealers", "0004_dealerprofile_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="store_dealer",
            field=models.ForeignKey(
                blank=True,
                help_text="Buyer đăng ký qua gian hàng đại lý — mỗi dealer một account riêng",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="storefront_buyers",
                to="dealers.dealerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role__in", ["admin", "supplier", "dealer"])),
                fields=("email",),
                name="unique_email_global_roles",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "buyer")),
                fields=("store_dealer", "email"),
                name="unique_buyer_email_per_dealer",
            ),
        ),
    ]
