# Generated by Django 6.0.5 on 2026-06-21 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0005_category_scope"),
        ("suppliers", "0008_supplier_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                (
                    "default_unit",
                    models.CharField(
                        help_text="Đơn vị mặc định (kg, bó...)", max_length=50
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Hoạt động"), ("inactive", "Ngừng dùng")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_masters",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "db_table": "product_masters",
                "ordering": ["sort_order", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("suggested_name", models.CharField(max_length=255)),
                ("default_unit", models.CharField(blank=True, max_length=50)),
                ("note", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ duyệt"),
                            ("approved", "Đã duyệt"),
                            ("rejected", "Từ chối"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Danh mục system admin gán khi duyệt",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_product_suggestions",
                        to="categories.category",
                    ),
                ),
                (
                    "product_master",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggestions",
                        to="product_catalog.productmaster",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_product_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suggested_category",
                    models.ForeignKey(
                        help_text="Danh mục NCC chọn (system hoặc custom) — admin map sang system khi duyệt",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_suggestions",
                        to="categories.category",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_suggestions",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "db_table": "product_suggestions",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="productmaster",
            constraint=models.UniqueConstraint(
                fields=("category", "slug"),
                name="unique_product_master_slug_per_category",
            ),
        ),
    ]
