# Generated by Django 6.0.5 on 2026-06-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_catalog", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductSuggestion",
        ),
    ]
