# Generated by Django 6.0.5 on 2026-06-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_catalog", "0002_delete_productsuggestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Mã slug, vd. spring, summer", unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Tên hiển thị, vd. Xuân, Hè", max_length=100
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "start_month",
                    models.PositiveSmallIntegerField(help_text="Tháng bắt đầu (1–12)"),
                ),
                (
                    "end_month",
                    models.PositiveSmallIntegerField(help_text="Tháng kết thúc (1–12)"),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Hoạt động"), ("inactive", "Ngừng dùng")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "seasons",
                "ordering": ["sort_order", "name", "id"],
            },
        ),
        migrations.AddField(
            model_name="productmaster",
            name="seasons",
            field=models.ManyToManyField(
                blank=True,
                help_text="Mùa vụ thu hoạch / tiêu thụ điển hình của sản phẩm",
                related_name="product_masters",
                to="product_catalog.season",
            ),
        ),
    ]
