# Generated by Django 6.0.5 on 2026-07-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_catalog", "0003_season_and_product_master_seasons"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmaster",
            name="seasons",
        ),
        migrations.DeleteModel(
            name="Season",
        ),
    ]
