# Generated by Django 6.0.5 on 2026-07-16 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0002_remove_dealercustomer_unique_dealer_customer_and_more"),
        ("dealers", "0006_dealer_slug_store_code_help_text"),
        ("orders", "0004_order_delivery_reschedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DealerLoyaltySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points_per_unit",
                    models.PositiveIntegerField(
                        default=10000,
                        help_text="Số tiền (VND) quy đổi thành 1 điểm, vd. 10000 = 1 điểm.",
                    ),
                ),
                (
                    "include_shipping_in_points",
                    models.BooleanField(
                        default=False,
                        help_text="Nếu bật, tính điểm trên total_amount (gồm phí ship).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dealer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_config",
                        to="dealers.dealerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loyalty Config",
                "verbose_name_plural": "Loyalty Configs",
                "db_table": "loyalty_configs",
            },
        ),
        migrations.CreateModel(
            name="LoyaltyTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=100)),
                ("level", models.PositiveSmallIntegerField()),
                ("min_points", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("benefits", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="Hạng mặc định do hệ thống tạo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_tiers",
                        to="dealers.dealerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "loyalty_tiers",
                "ordering": ["level", "min_points", "id"],
            },
        ),
        migrations.CreateModel(
            name="CustomerTierHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tier_histories",
                        to="customers.customerprofile",
                    ),
                ),
                (
                    "new_tier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tier_history_to",
                        to="loyalty.loyaltytier",
                    ),
                ),
                (
                    "old_tier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tier_history_from",
                        to="loyalty.loyaltytier",
                    ),
                ),
            ],
            options={
                "db_table": "customer_tier_histories",
                "ordering": ["-changed_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyPointTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("ORDER_REWARD", "Cộng điểm từ đơn hàng"),
                            ("RETURN_DEDUCTION", "Trừ điểm do hoàn hàng"),
                            ("MANUAL_ADD", "Cộng điểm thủ công"),
                            ("MANUAL_DEDUCT", "Trừ điểm thủ công"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        help_text="Số điểm thay đổi (luôn dương, loại giao dịch quyết định cộng/trừ)."
                    ),
                ),
                ("balance_before", models.PositiveIntegerField()),
                ("balance_after", models.PositiveIntegerField()),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loyalty_point_transactions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_point_transactions",
                        to="customers.customerprofile",
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_point_transactions",
                        to="dealers.dealerprofile",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loyalty_point_transactions",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "loyalty_point_transactions",
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("transaction_type", "ORDER_REWARD")),
                        fields=("order",),
                        name="unique_order_reward_loyalty_transaction",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="loyaltytier",
            constraint=models.UniqueConstraint(
                fields=("dealer", "code"), name="unique_loyalty_tier_code_per_dealer"
            ),
        ),
        migrations.AddConstraint(
            model_name="loyaltytier",
            constraint=models.UniqueConstraint(
                fields=("dealer", "level"), name="unique_loyalty_tier_level_per_dealer"
            ),
        ),
    ]
