# Generated by Django 6.0.5 on 2026-06-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_inventory', '0002_alter_inventorybatch_import_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorybatch',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
