# Generated by Django 6.0.5 on 2026-06-15 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_existing_buyer_profiles(apps, schema_editor):
    Account = apps.get_model("accounts", "Account")
    CustomerProfile = apps.get_model("customers", "CustomerProfile")
    profiles = [
        CustomerProfile(user=account)
        for account in Account.objects.filter(role="buyer")
        if not CustomerProfile.objects.filter(user=account).exists()
    ]
    CustomerProfile.objects.bulk_create(profiles, ignore_conflicts=True)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0005_category_scope"),
        ("dealers", "0003_dealerprofile_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_orders", models.PositiveIntegerField(default=0)),
                (
                    "total_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("loyalty_points", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "favorite_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="favorite_customer_profiles",
                        to="categories.category",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Profile",
                "verbose_name_plural": "Customer Profiles",
                "db_table": "customer_profiles",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receiver_name", models.CharField(max_length=255)),
                ("receiver_phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="customers.customerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Address",
                "verbose_name_plural": "Customer Addresses",
                "db_table": "customer_addresses",
                "ordering": ["-is_default", "-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("customer",),
                        name="unique_default_customer_address",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DealerCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_orders", models.PositiveIntegerField(default=0)),
                (
                    "total_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("loyalty_points", models.PositiveIntegerField(default=0)),
                ("last_order_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dealer_customers",
                        to="customers.customerprofile",
                    ),
                ),
                (
                    "dealer_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dealer_customers",
                        to="dealers.dealerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dealer Customer",
                "verbose_name_plural": "Dealer Customers",
                "db_table": "dealer_customers",
                "ordering": ["-last_order_at", "-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dealer_profile", "customer"),
                        name="unique_dealer_customer",
                    )
                ],
            },
        ),
        migrations.RunPython(create_existing_buyer_profiles, migrations.RunPython.noop),
    ]
