# Generated by Django 6.0.5 on 2026-06-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dealercustomer",
            name="unique_dealer_customer",
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="last_order_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="note",
            field=models.TextField(
                blank=True, help_text="Ghi chú nội bộ của đại lý về khách hàng"
            ),
        ),
        migrations.DeleteModel(
            name="DealerCustomer",
        ),
    ]
