# Generated by Django 6.0.5 on 2026-07-16 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_remove_dealercustomer_unique_dealer_customer_and_more"),
        ("loyalty", "0001_loyalty_tiers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="current_tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="loyalty.loyaltytier",
            ),
        ),
    ]
