# Generated by Django 6.0.5 on 2026-06-16 13:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0002_remove_dealercustomer_unique_dealer_customer_and_more"),
        ("dealer_products", "0004_dealerproduct_category"),
        ("dealers", "0004_dealerprofile_logo"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_reviews",
                        to="customers.customerprofile",
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_reviews",
                        to="dealers.dealerprofile",
                    ),
                ),
                (
                    "dealer_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="dealer_products.dealerproduct",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_reviews",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "product_reviews",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ReviewImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(blank=True, upload_to="review_images/")),
                ("image_url", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="reviews.productreview",
                    ),
                ),
            ],
            options={
                "db_table": "review_images",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ProductRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.DecimalField(decimal_places=4, max_digits=8)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("similar_product", "Sản phẩm tương tự"),
                            ("frequently_bought", "Thường mua cùng"),
                            ("personalized", "Cá nhân hóa"),
                            ("segment_based", "Theo nhóm khách"),
                        ],
                        max_length=30,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_recommendations",
                        to="customers.customerprofile",
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_recommendations",
                        to="dealers.dealerprofile",
                    ),
                ),
                (
                    "dealer_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="dealer_products.dealerproduct",
                    ),
                ),
            ],
            options={
                "db_table": "product_recommendations",
                "ordering": ["-score", "-updated_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["customer", "recommendation_type", "-score"],
                        name="product_rec_custome_e22738_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("customer", "dealer_product", "recommendation_type"),
                        name="unique_product_recommendation",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(
                fields=["dealer_product", "-created_at"],
                name="product_rev_dealer__81d3ef_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="productreview",
            constraint=models.UniqueConstraint(
                fields=("customer_profile", "dealer_product", "order"),
                name="unique_product_review_per_order",
            ),
        ),
    ]
