# Generated by Django 6.0.5 on 2026-06-16 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0002_remove_dealercustomer_unique_dealer_customer_and_more"),
        ("dealer_products", "0004_dealerproduct_category"),
        ("dealers", "0004_dealerprofile_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Mã nội bộ: vip, loyal, new, organic_lover...",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="true nếu là segment mẫu do hệ thống tạo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_segments",
                        to="dealers.dealerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "customer_segments",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="CustomerSegmentMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segment_memberships",
                        to="customers.customerprofile",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="marketing.customersegment",
                    ),
                ),
            ],
            options={
                "db_table": "customer_segment_members",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CustomerInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("add_cart_count", models.PositiveIntegerField(default=0)),
                ("purchase_count", models.PositiveIntegerField(default=0)),
                ("last_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("last_added_at", models.DateTimeField(blank=True, null=True)),
                ("last_purchased_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_interactions",
                        to="customers.customerprofile",
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_interactions",
                        to="dealers.dealerprofile",
                    ),
                ),
                (
                    "dealer_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_interactions",
                        to="dealer_products.dealerproduct",
                    ),
                ),
            ],
            options={
                "db_table": "customer_interactions",
                "ordering": ["-updated_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["dealer", "-updated_at"],
                        name="customer_in_dealer__8cfcaf_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("customer", "dealer_product"),
                        name="unique_customer_product_interaction",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="customersegment",
            constraint=models.UniqueConstraint(
                fields=("dealer", "code"),
                name="unique_customer_segment_code_per_dealer",
            ),
        ),
        migrations.AddConstraint(
            model_name="customersegmentmember",
            constraint=models.UniqueConstraint(
                fields=("customer_profile", "segment"),
                name="unique_customer_segment_membership",
            ),
        ),
    ]
