# Generated by Django 6.0.5 on 2026-06-27 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealers", "0004_dealerprofile_logo"),
        ("marketing", "0001_initial"),
        ("supplier_products", "0008_supplierproduct_product_master_and_more"),
        ("suppliers", "0008_supplier_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="DealerSupplierProductInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("add_cart_count", models.PositiveIntegerField(default=0)),
                ("purchase_count", models.PositiveIntegerField(default=0)),
                ("last_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("last_added_at", models.DateTimeField(blank=True, null=True)),
                ("last_purchased_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_product_interactions",
                        to="dealers.dealerprofile",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dealer_product_interactions",
                        to="suppliers.supplier",
                    ),
                ),
                (
                    "supplier_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dealer_interactions",
                        to="supplier_products.supplierproduct",
                    ),
                ),
            ],
            options={
                "db_table": "dealer_supplier_product_interactions",
                "ordering": ["-updated_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["supplier", "-updated_at"],
                        name="dealer_supp_supplie_7f6aa2_idx",
                    ),
                    models.Index(
                        fields=["dealer", "-updated_at"],
                        name="dealer_supp_dealer__df6186_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dealer", "supplier_product"),
                        name="unique_dealer_supplier_product_interaction",
                    )
                ],
            },
        ),
    ]
