# Generated by Django 6.0.5 on 2026-07-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0002_dealer_supplier_product_interactions"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="customersegment",
            name="unique_customer_segment_code_per_dealer",
        ),
        migrations.AddConstraint(
            model_name="customersegment",
            constraint=models.UniqueConstraint(
                fields=("code",), name="unique_customer_segment_code"
            ),
        ),
        migrations.RemoveField(
            model_name="customersegment",
            name="dealer",
        ),
    ]
