# Generated by Django 6.0.5 on 2026-07-01 09:26

from django.db import migrations, models


def apply_customer_segment_schema_changes(apps, schema_editor):
    """Áp dụng thay đổi schema an toàn khi DB đã bị chỉnh tay trước đó."""
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            ALTER TABLE customer_segments
            DROP CONSTRAINT IF EXISTS unique_customer_segment_code_per_dealer;
            """
        )
        cursor.execute(
            """
            ALTER TABLE customer_segments
            DROP COLUMN IF EXISTS dealer_id CASCADE;
            """
        )
        cursor.execute(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'unique_customer_segment_code'
                ) THEN
                    ALTER TABLE customer_segments
                    ADD CONSTRAINT unique_customer_segment_code UNIQUE (code);
                END IF;
            END $$;
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0002_dealer_supplier_product_interactions"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    apply_customer_segment_schema_changes,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="customersegment",
                    name="unique_customer_segment_code_per_dealer",
                ),
                migrations.AddConstraint(
                    model_name="customersegment",
                    constraint=models.UniqueConstraint(
                        fields=("code",),
                        name="unique_customer_segment_code",
                    ),
                ),
                migrations.RemoveField(
                    model_name="customersegment",
                    name="dealer",
                ),
            ],
        ),
    ]
