# Generated by Django 6.0.5 on 2026-07-07 08:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_assign_passive_segment_to_existing_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSegmentationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_id', models.IntegerField(verbose_name='Mã đại lý')),
                ('silhouette_score', models.FloatField(verbose_name='Điểm Silhouette Score')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian thực hiện')),
            ],
            options={
                'verbose_name': 'Lịch sử phân loại AI',
                'verbose_name_plural': 'Lịch sử phân loại AI',
                'db_table': 'marketing_customer_segmentation_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
