# Generated by Django 6.0.5 on 2026-07-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_customersegmentationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersegmentationhistory',
            name='passive_count',
            field=models.IntegerField(default=0, verbose_name='Số khách hàng thụ động'),
        ),
        migrations.AddField(
            model_name='customersegmentationhistory',
            name='potential_count',
            field=models.IntegerField(default=0, verbose_name='Số khách hàng tiềm năng'),
        ),
        migrations.AddField(
            model_name='customersegmentationhistory',
            name='risk_count',
            field=models.IntegerField(default=0, verbose_name='Số khách hàng rủi ro'),
        ),
        migrations.AddField(
            model_name='customersegmentationhistory',
            name='total_customers',
            field=models.IntegerField(default=0, verbose_name='Tổng số khách hàng được phân loại'),
        ),
        migrations.AddField(
            model_name='customersegmentationhistory',
            name='vip_count',
            field=models.IntegerField(default=0, verbose_name='Số khách hàng VIP'),
        ),
        migrations.AlterField(
            model_name='customersegmentationhistory',
            name='dealer_id',
            field=models.IntegerField(default=0, verbose_name='Mã đại lý'),
        ),
        migrations.AlterField(
            model_name='customersegmentationhistory',
            name='silhouette_score',
            field=models.FloatField(default=0.0, verbose_name='Điểm Silhouette Score'),
        ),
    ]
