export const MOCK_REVIEW_SUMMARY = {
    average: 4.8,
    total: 23,
    distribution: [
        { stars: 5, percent: 78 },
        { stars: 4, percent: 14 },
        { stars: 3, percent: 5 },
        { stars: 2, percent: 2 },
        { stars: 1, percent: 1 },
    ],
};

export const MOCK_PRODUCT_REVIEWS = [
    {
        id: 1,
        name: "Lê Minh Anh",
        initial: "L",
        meta: "Đã mua hàng • 2 ngày trước",
        rating: 5,
        content: "Rau tươi, lá xanh đẹp, nấu canh rất ngon. Giao hàng nhanh, đóng gói cẩn thận.",
    },
    {
        id: 2,
        name: "Hoàng Nam",
        initial: "H",
        meta: "Đã mua hàng • 5 ngày trước",
        rating: 5,
        content: "Chất lượng ổn, giá hợp lý so với chợ. Sẽ đặt thêm tuần sau.",
    },
    {
        id: 3,
        name: "Phạm Thu Hà",
        initial: "P",
        meta: "Đã mua hàng • 1 tuần trước",
        rating: 4,
        content: "Rau sạch, ít sâu. Chỉ hơi úa một chút ở lá ngoài nhưng vẫn dùng được.",
    },
    {
        id: 4,
        name: "Nguyễn Văn Bình",
        initial: "N",
        meta: "Đã mua hàng • 1 tuần trước",
        rating: 5,
        content: "Mua lần thứ 3 rồi, luôn hài lòng. Rau giòn, thơm mùi đồng.",
    },
    {
        id: 5,
        name: "Trần Thị Lan",
        initial: "T",
        meta: "Đã mua hàng • 2 tuần trước",
        rating: 5,
        content: "Đúng như mô tả, rau organic sạch. Cả nhà đều khen.",
    },
    {
        id: 6,
        name: "Đỗ Quang Huy",
        initial: "Đ",
        meta: "Đã mua hàng • 2 tuần trước",
        rating: 4,
        content: "Tốt, giao đúng giờ. Mong shop bổ sung thêm loại rau theo mùa.",
    },
    {
        id: 7,
        name: "Võ Thị Mai",
        initial: "V",
        meta: "Đã mua hàng • 3 tuần trước",
        rating: 5,
        content: "Rau rất tươi, luộc ăn ngọt tự nhiên. Đóng gói bằng túi giấy thân thiện.",
    },
    {
        id: 8,
        name: "Bùi Minh Tuấn",
        initial: "B",
        meta: "Đã mua hàng • 3 tuần trước",
        rating: 3,
        content: "Lần này hơi ít hơn lần trước một chút, nhưng chất lượng vẫn ổn.",
    },
    {
        id: 9,
        name: "Lý Hồng Nhung",
        initial: "L",
        meta: "Đã mua hàng • 1 tháng trước",
        rating: 5,
        content: "Rau sạch, không mùi hóa chất. Trẻ nhà ăn rất thích.",
    },
    {
        id: 10,
        name: "Cao Đình Phúc",
        initial: "C",
        meta: "Đã mua hàng • 1 tháng trước",
        rating: 4,
        content: "Giao nhanh, rau tươi. Giá cao hơn chợ một chút nhưng đáng tiền.",
    },
    {
        id: 11,
        name: "Hà Thị Thu",
        initial: "H",
        meta: "Đã mua hàng • 1 tháng trước",
        rating: 5,
        content: "Xào ăn giòn, không bị đắng. Sẽ giới thiệu cho bạn bè.",
    },
    {
        id: 12,
        name: "Phan Văn Đức",
        initial: "P",
        meta: "Đã mua hàng • 1 tháng trước",
        rating: 4,
        content: "Hàng chuẩn, nguồn gốc rõ ràng. Cần thêm ảnh thực tế trên web.",
    },
    {
        id: 13,
        name: "Ngô Thị Hương",
        initial: "N",
        meta: "Đã mua hàng • 1 tháng trước",
        rating: 5,
        content: "Rau organic đúng nghĩa, ăn yên tâm cho cả gia đình.",
    },
    {
        id: 14,
        name: "Trịnh Quốc Anh",
        initial: "T",
        meta: "Đã mua hàng • 2 tháng trước",
        rating: 4,
        content: "Chất lượng ổn định qua nhiều lần mua. Dịch vụ chu đáo.",
    },
    {
        id: 15,
        name: "Đinh Thị Oanh",
        initial: "Đ",
        meta: "Đã mua hàng • 2 tháng trước",
        rating: 5,
        content: "Rau tươi ngon, đem đi biếu cũng được khen. Rất hài lòng!",
    },
    {
        id: 16,
        name: "Lương Văn Hải",
        initial: "L",
        meta: "Đã mua hàng • 2 tháng trước",
        rating: 5,
        content: "Luôn đặt cố định mỗi tuần. Rau sạch, giao đúng hẹn.",
    },
    {
        id: 17,
        name: "Vũ Thị Ngọc",
        initial: "V",
        meta: "Đã mua hàng • 2 tháng trước",
        rating: 4,
        content: "Ngon, tươi. Hy vọng có thêm combo rau mix tiết kiệm.",
    },
    {
        id: 18,
        name: "Hoàng Thị Linh",
        initial: "H",
        meta: "Đã mua hàng • 3 tháng trước",
        rating: 5,
        content: "Rau rất sạch, không thấy sâu hay đốm vàng. Recommend!",
    },
    {
        id: 19,
        name: "Mai Văn Thắng",
        initial: "M",
        meta: "Đã mua hàng • 3 tháng trước",
        rating: 3,
        content: "Ổn nhưng lần này giao hơi trễ so với khung giờ đã chọn.",
    },
    {
        id: 20,
        name: "Chu Thị Hồng",
        initial: "C",
        meta: "Đã mua hàng • 3 tháng trước",
        rating: 5,
        content: "Rau muống giòn, xào tỏi thơm lừng. Cảm ơn shop!",
    },
    {
        id: 21,
        name: "Tạ Minh Khôi",
        initial: "T",
        meta: "Đã mua hàng • 3 tháng trước",
        rating: 4,
        content: "Chất lượng tốt, giá phù hợp. Sẽ tiếp tục ủng hộ.",
    },
    {
        id: 22,
        name: "Lê Thị Hoa",
        initial: "L",
        meta: "Đã mua hàng • 4 tháng trước",
        rating: 5,
        content: "Rau organic chuẩn, nấu canh chua rất ngon miệng.",
    },
    {
        id: 23,
        name: "Nguyễn Đức Thành",
        initial: "N",
        meta: "Đã mua hàng • 4 tháng trước",
        rating: 5,
        content: "Mua nhiều lần, chưa bao giờ thất vọng. Rau luôn tươi mới.",
    },
];

export const REVIEWS_PER_PAGE = 5;
