# Generated by Django 6.0.5 on 2026-06-05 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier_products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplierproduct",
            name="thumbnail",
        ),
        migrations.CreateModel(
            name="SupplierProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(max_length=500)),
                ("is_thumbnail", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "supplier_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="supplier_products.supplierproduct",
                    ),
                ),
            ],
            options={
                "db_table": "supplier_product_images",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
