# Generated by Django 6.0.5 on 2026-06-05 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier_products", "0002_remove_supplierproduct_thumbnail_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CultivationProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_order", models.IntegerField()),
                ("process_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "supplier_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cultivation_processes",
                        to="supplier_products.supplierproduct",
                    ),
                ),
            ],
            options={
                "db_table": "cultivation_processes",
                "ordering": ["step_order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("supplier_product", "step_order"),
                        name="unique_product_step_order",
                    )
                ],
            },
        ),
    ]
