# Generated by Django 6.0.5 on 2026-06-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier_products", "0003_cultivationprocess"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierproductimage",
            name="image_url",
            field=models.FileField(upload_to="product_images/"),
        ),
    ]
