# Generated by Django 6.0.5 on 2026-06-07 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplier_products", "0004_alter_supplierproductimage_image_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplierproduct",
            options={
                "ordering": ["-updated_at", "-created_at", "-id"],
                "verbose_name": "Supplier Product",
                "verbose_name_plural": "Supplier Products",
            },
        ),
    ]
