# Generated by Django 6.0.5 on 2026-06-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier_products", "0005_alter_supplierproduct_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierproduct",
            name="wholesale_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Giá bán sỉ cho đại lý (snapshot vào phiếu nhập khi tạo đơn)",
                max_digits=12,
                null=True,
            ),
        ),
    ]
