# Generated by Django 6.0.5 on 2026-06-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier_products", "0006_supplierproduct_wholesale_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierproduct",
            name="daily_production_capacity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Năng lực sản xuất trung bình mỗi ngày (cùng đơn vị với unit)",
                max_digits=12,
                null=True,
            ),
        ),
    ]
