# Generated by Django 6.0.5 on 2026-06-21 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0005_category_scope"),
        ("product_catalog", "0001_initial"),
        ("supplier_products", "0007_supplierproduct_daily_production_capacity"),
        ("suppliers", "0008_supplier_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierproduct",
            name="product_master",
            field=models.ForeignKey(
                blank=True,
                help_text="Catalog chuẩn — bắt buộc với danh mục system; tuỳ chọn với danh mục riêng",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_products",
                to="product_catalog.productmaster",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierproduct",
            constraint=models.UniqueConstraint(
                condition=models.Q(("product_master__isnull", False)),
                fields=("supplier", "product_master"),
                name="unique_supplier_product_master",
            ),
        ),
    ]
