# Generated by Django — quantity discount policies

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("suppliers", "0001_initial"),
        ("supplier_products", "0008_supplierproduct_product_master_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuantityDiscountPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("all", "Tất cả sản phẩm"),
                            ("category", "Theo danh mục"),
                            ("supplier_product", "Theo sản phẩm NCC"),
                        ],
                        max_length=20,
                    ),
                ),
                ("priority", models.PositiveIntegerField(default=0, help_text="Cao hơn thắng khi nhiều policy cùng scope")),
                ("is_active", models.BooleanField(default=True)),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quantity_discount_policies",
                        to="categories.category",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quantity_discount_policies",
                        to="suppliers.supplier",
                    ),
                ),
                (
                    "supplier_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quantity_discount_policies",
                        to="supplier_products.supplierproduct",
                    ),
                ),
            ],
            options={
                "db_table": "quantity_discount_policies",
                "ordering": ["-priority", "-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="QuantityDiscountTier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "min_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Số lượng tối thiểu để áp dụng bậc giảm",
                        max_digits=12,
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percent", "Theo phần trăm"),
                            ("fixed", "Số tiền cố định"),
                        ],
                        max_length=10,
                    ),
                ),
                ("discount_value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="supplier_products.quantitydiscountpolicy",
                    ),
                ),
            ],
            options={
                "db_table": "quantity_discount_tiers",
                "ordering": ["sort_order", "min_quantity", "id"],
            },
        ),
    ]
